name: intake-thredds-dev
channels:
  - conda-forge
dependencies:
  - python=*=*cp*
  - aiohttp
  - codecov
  - fsspec>=0.8.5
  - h5netcdf>=0.8.1
  - intake-xarray>=0.3
  - netcdf4
  - pip
  - pre-commit
  - pydap
  - pytest
  - pytest-cov
  - pytest-icdiff
  - pytest-xdist
  - tqdm
  - xarray
  - cfgrib
  - pip:
      - git+https://github.com/intake/intake.git
      - git+https://github.com/Unidata/siphon.git
