name: Nightly CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *" # Daily “At 00:00” UTC
  workflow_dispatch: # allows you to trigger the workflow run manually

jobs:
  upstream-dev:
    name: upstream-dev
    runs-on: ubuntu-latest
    if: github.repository == 'intake/intake-thredds'
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v4

      - name: set up conda environment
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: ci/environment-upstream-dev.yml
          init-shell: >-
            bash
          cache-environment: true
          cache-downloads: true
          post-cleanup: "all"
          create-args: |
            python=3.12

      - name: Install intake-thredds
        run: |
          python -m pip install . --no-deps
          conda list

      - name: Run Tests
        if: success()
        id: tests
        run: |
          python -m pytest --report-log=pytest-log.jsonl

      - name: Generate and publish the report
        if: |
          failure()
          && steps.status.outcome == 'failure'
          && github.event_name == 'schedule'
          && github.repository_owner == 'intake'
        uses: xarray-contrib/issue-from-pytest-log@v1
        with:
          log-path: pytest-log.jsonl
